# Generated by Django 4.1.2 on 2023-01-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Характеристика'),
        ),
    ]
